### ISSUE TITLE
Improve portability/modularity

### ISSUE THREAD

**Issue by panicbit** [panicbit/rust#1]
1. Extract modules from libstd into crates.
    Many of the dependent modules have a cyclic dependency,
    which should be resolved by either moving items into their own crate
    or into either of the modules, to create an acyclic dependency tree.
    - [ ] `sys`
        - [ ] `sync` | Required items: `Once`
        - [ ] `time` | Required items: `Duration`
        - [x] `error`
        - [ ] `io` | Required items: `self`, `prelude::*`, `Error`, `ErrorKind`
        - [x] `ascii`
        - [ ] `ffi` | Required items: `CStr`, `CString`, `OsString`
        - [ ] `os` | Required items: `OsStringExt` and more
        - [ ] `fs` | Required items: `File`
              Possible (temporary) resolution: Move `sys::{unix, windows}::ext` to `std::os::{unix, windows}`.
              Every instance of `std::fs` can probably be replaced with `sys::fs`.
        - [ ] `path`
        - [ ] `net` | Required items: `SocketAddr`, `Shutdown`, `Ipv4Addr`, `Ipv6Addr`
        - [ ] `thread` | Required items: `current`, `thread_local!` and friends
        - [ ] `env` | Required items: `var`, `var_os`
        - [ ] `collections::hash_map`
    - [ ] `collections::hash_map`
        - [ ] `thread`
    - [ ] `thread`
        - [ ] `io`
        - [ ] `sys::thread`
        - [ ] `panicking`
    - [ ] `sys::thread`
        - [ ] `io`
    - [ ] `io`
        - [x] `error`
        - [ ] `sys::mutex`
        - [ ] `sys_common::io` | The only item is `DEFAULT_BUF_SIZE`
        - [ ] `sys::stdio`
        - [ ] `sys_common::remutex`
    - [x] `error` → `libstd_error`
    - [x] `ascii` → `libstd_ascii`
    - [ ] `sys::mutex`
    - [ ] `sys_common::remutex`
        - [ ] `sys_common::poison`
    - [ ] `sys_common::poison`
        - [ ] `thread`
    - [ ] panicking
        - [ ] `thread`
        - [ ] `io`
        - [ ] `sys_common::rwlock`
        - [ ] `sys_common::thread_info`
        - [ ] `sys_common::util`

    Cycles:
        - `sys` → `collections::hash_map` → `thread` → `sys`
        - `thread` → `sys` → `thread`
        -  `io` → `sys` → `thread` → `io`
        - … a lot more

2. TBD

Branch: https://github.com/panicbit/rust/commits/refactor

**Comment by jethrogb** [comment]
collections | required items: rand

**Comment by panicbit** [comment]
Superseded by #2
